language: python
python:
    - "3.6"

script: python star.py -t $GITHUB_TOKEN > README.md

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    target-branch: master
    on:
        branch: master
